package com.project.ems.security.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Entity representing an application user.
 *
 * A user can log in to the system and is assigned exactly one role.
 *
 * Future enhancements supported by this entity:
 * - JWT Authentication
 * - Password Reset
 * - Email Verification
 * - Last Login Tracking
 * - Profile Management
 * - Account Locking
 */
@Entity
@Table(
        name = "users",
        uniqueConstraints = {
                // Username must be unique
                @UniqueConstraint(columnNames = "username"),

                // Email must also be unique
                @UniqueConstraint(columnNames = "email")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * Primary Key.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Username used for login.
     *
     * Example:
     * vishwajeet
     */
    @Column(nullable = false, length = 50)
    private String username;

    /**
     * User's email address.
     * Must be unique.
     */
    @Column(nullable = false, length = 100)
    private String email;

    /**
     * Encrypted password.
     *
     * Never store plain-text passwords.
     * Passwords will be encrypted using BCrypt.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Indicates whether the user's account is enabled.
     *
     * Example:
     * true  -> User can log in
     * false -> Account disabled by admin
     */
    @Builder.Default
    @Column(nullable = false)
    private Boolean enabled = true;

    /**
     * Indicates whether the account is locked.
     *
     * Example:
     * true  -> User can log in
     * false -> Account locked
     */
    @Builder.Default
    @Column(nullable = false)
    private Boolean accountNonLocked = true;

    /**
     * Time when the user account was created.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Time when the user account was last updated.
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Time of the user's last successful login.
     *
     * Initially null until the user logs in.
     */
    private LocalDateTime lastLogin;

    /**
     * Many Users can belong to one Role.
     *
     * Example:
     *
     * ADMIN
     *   ├── User1
     *   ├── User2
     *   └── User3
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)

    // Foreign key column in the users table
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    /**
     * Automatically executed before the entity
     * is inserted into the database.
     */
    @PrePersist
    public void prePersist() {

        LocalDateTime now = LocalDateTime.now();

        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Automatically executed before updating
     * an existing record.
     */
    @PreUpdate
    public void preUpdate() {

        this.updatedAt = LocalDateTime.now();
    }
}