package com.project.ems.security.config;

import com.project.ems.security.jwt.JwtAuthenticationFilter;
import jakarta.servlet.DispatcherType;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.Customizer;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

/**
 * Main Spring Security configuration.
 *
 * The React pages and static resources are public.
 * Business data remains protected under /api/** using JWT.
 */
@Configuration
@EnableMethodSecurity
@RequiredArgsConstructor
public class SecurityConfig {

    /**
     * Custom filter responsible for reading and validating JWT tokens.
     */
    private final JwtAuthenticationFilter jwtAuthenticationFilter;

    /**
     * Configures public frontend routes, secured APIs,
     * role-based permissions and stateless authentication.
     *
     * @param http Spring Security configuration
     * @return configured security filter chain
     * @throws Exception when the configuration cannot be created
     */
    @Bean
    public SecurityFilterChain securityFilterChain(
            HttpSecurity http) throws Exception {

        http
                /*
                 * The application uses stateless JWT authentication
                 * instead of browser sessions and CSRF tokens.
                 */
                .csrf(AbstractHttpConfigurer::disable)

                /*
                 * Use Spring's configured CORS support.
                 */
                .cors(Customizer.withDefaults())

                /*
                 * Spring Security will not create an HTTP session.
                 *
                 * Each protected request must send:
                 * Authorization: Bearer <JWT>
                 */
                .sessionManagement(session ->
                        session.sessionCreationPolicy(
                                SessionCreationPolicy.STATELESS
                        )
                )

                .authorizeHttpRequests(authorize -> authorize

                        /*
                         * SpaController forwards React routes to index.html.
                         *
                         * Spring Security also checks internal FORWARD
                         * requests, so they must be explicitly permitted.
                         */
                        .dispatcherTypeMatchers(
                                DispatcherType.FORWARD,
                                DispatcherType.ERROR
                        )
                        .permitAll()

                        /*
                         * Public React routes.
                         *
                         * These routes only serve the React application.
                         * Protected business data is still loaded through
                         * secured /api/** endpoints.
                         */
                        .requestMatchers(
                                "/",
                                "/login",
                                "/dashboard",
                                "/employees",
                                "/leaves",
                                "/index.html"
                        )
                        .permitAll()

                        /*
                         * React static resources generated by Vite.
                         */
                        .requestMatchers(
                                "/assets/**",
                                "/favicon.ico",
                                "/*.js",
                                "/*.css",
                                "/*.svg",
                                "/*.png",
                                "/error"
                        )
                        .permitAll()

                        /*
                         * Registration and login APIs must be public.
                         */
                        .requestMatchers("/api/v1/auth/**")
                        .permitAll()

                        /*
                         * Swagger and OpenAPI documentation.
                         */
                        .requestMatchers(
                                "/swagger-ui.html",
                                "/swagger-ui/**",
                                "/v3/api-docs/**",
                                "/api-docs/**"
                        )
                        .permitAll()

                        /*
                         * ADMIN and HR can create employees.
                         */
                        .requestMatchers(
                                HttpMethod.POST,
                                "/api/v1/employees",
                                "/api/v1/employees/**"
                        )
                        .hasAnyRole("ADMIN", "HR")

                        /*
                         * ADMIN and HR can update employees.
                         */
                        .requestMatchers(
                                HttpMethod.PUT,
                                "/api/v1/employees",
                                "/api/v1/employees/**"
                        )
                        .hasAnyRole("ADMIN", "HR")

                        /*
                         * Only ADMIN can delete employees.
                         */
                        .requestMatchers(
                                HttpMethod.DELETE,
                                "/api/v1/employees",
                                "/api/v1/employees/**"
                        )
                        .hasRole("ADMIN")

                        /*
                         * Any logged-in user can view and search employees.
                         */
                        .requestMatchers(
                                HttpMethod.GET,
                                "/api/v1/employees",
                                "/api/v1/employees/**"
                        )
                        .authenticated()

                        /*
                         * Every leave endpoint requires authentication.
                         *
                         * Additional ADMIN/HR restrictions are applied
                         * through @PreAuthorize in LeaveController.
                         */
                        .requestMatchers(
                                "/api/v1/leaves",
                                "/api/v1/leaves/**"
                        )
                        .authenticated()

                        /*
                         * Any future endpoint under /api also requires
                         * a valid authenticated user by default.
                         */
                        .requestMatchers("/api/**")
                        .authenticated()

                        /*
                         * Remaining non-API requests may serve frontend
                         * resources and React routes.
                         */
                        .anyRequest()
                        .permitAll()
                )

                /*
                 * The project uses a custom React login page.
                 */
                .formLogin(AbstractHttpConfigurer::disable)

                /*
                 * HTTP Basic authentication is not used.
                 */
                .httpBasic(AbstractHttpConfigurer::disable)

                /*
                 * Run JWT validation before Spring Security's
                 * username/password filter.
                 */
                .addFilterBefore(
                        jwtAuthenticationFilter,
                        UsernamePasswordAuthenticationFilter.class
                );

        return http.build();
    }
}